# Select language
language: python

# Select python version
python:
# - "2.6" paramiko not supported
 - "2.7"
# - "3.2" texttable is not supporting this version!
# - "3.3" paramiko not supported
# - "3.4" error due to canari now requiring 3.5: https://travis-ci.org/zdresearch/OWASP-Nettacker/jobs/624877324#L282
 - "3.5"
 - "3.6"
 - "3.6-dev"
# - "3.7-dev" error at the moment: https://travis-ci.org/viraintel/OWASP-Nettacker/jobs/332849350
# - "nightly" error at the moment: https://travis-ci.org/viraintel/OWASP-Nettacker/jobs/332849351

# Select OS
os:
 - "linux"

# Install requirements
install:
 - "pip install --upgrade wheel"
 - "pip install --upgrade setuptools codacy-coverage coverage"
 - "pip install --upgrade -r requirements.txt"
 # scapy has different name in python 2.x and 3.x
 - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install scapy; else pip install scapy-python3; fi

# Run
script:
- "python scripts/__travis_test__.py"
- if [[ ${#CODACY_PROJECT_TOKEN} == 32 ]];
    then
      coverage run nettacker.py -i 127.0.0.1 -m all -t 1000 &&
      coverage report -m &&
      coverage xml &&
      python-codacy-coverage -r coverage.xml;
      else
        echo "skip code coverage section";
  fi;
