version: "3"

services:
  nettacker:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: python3 nettacker.py --start-api --api-host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/owaspnettacker
    environment:
      - docker_env=true
